package EventListeners;

/**
 * Interface that implements the handleFormSubmit method for the EventListener class.
 */
public interface FormListener extends EventListener {

	/**
	 * Notifies the listener that a form is submitted
	 * @param action -  the string generated by the form
	 */
	void runUrlAttribute(String action);
}
